### PR TITLE
Added support for 3 extensions

### PR DESCRIPTION
**Pull request by Fxvoid**
Added support for [ADetailer](https://github.com/Bing-su/adetailer), [Multiduffusion upscale](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111) and [Dynamic Prompts](https://github.com/adieyal/sd-dynamic-prompts). Also had to implement some form of queuing for handling selects so they don't overlap.

### CODE REVIEW

**Comment by chuckkay** [comment]
thanks they work i wish the author would test and approve..
also any chance you can improve on his controlnet script to add the feature to save batch directory
also im using SDnext (Vlad Automatic - fork of automatic 1111) which is far better then Automatic 1111.  but things are slightly different now.  and State settings arent saved for "second pass" formerly hiresfix & the newly added refiner features.

**Comment by Fxvoid** [comment]
> thanks they work i wish the author would test and approve.. also any chance you can improve on his controlnet script to add the feature to save batch directory also im using SDnext (Vlad Automatic - fork of automatic 1111) which is far better then Automatic 1111. but things are slightly different now. and State settings arent saved for "second pass" formerly hiresfix & the newly added refiner features.

thank you for the positive feedback, I'll see what I can do as soon as I have spare time.

**Review by ilian6806 — APPROVED** [review]

**Comment by ilian6806** [comment]
Great! Thanks for your contribution!

**Comment by chuckkay** [comment]
also any chance you can improve on his controlnet script to add the feature to save batch directory
also im using SDnext (Vlad Automatic - fork of automatic 1111) which is far better then Automatic 1111. but things are slightly different now. and State settings arent saved for "second pass" formerly hiresfix & the newly added refiner features.

**Pull request merged**
